### ISSUE TITLE
Is it supposed to work on Node 12?

### ISSUE THREAD

**Issue by extricator** [ndaidong/bellajs#94]
I'm getting a crash under node 12. Given that it's been a while since it was last updated I decided to ask..

```
internal/modules/cjs/loader.js:1018
      internalBinding('errors').triggerUncaughtException(
                                ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/user/Development/VSCode/ProjectJS/node_modules/bellajs/dist/bella.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:969:13)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/Development/VSCode/ProjectJS/node_modules/article-parser/src/main.js:8:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by ndaidong** [comment]
@extricator hello, I'm using node 12 too. And this lib [has been tested with node 12](https://travis-ci.org/ndaidong/bellajs/jobs/584930639). Taking a look at your logs, I think the issue may relate to the way how you load your modules using esm. Could you share more your code?
